set_property PACKAGE_PIN T15 [get_ports CAN_1_tx]
set_property PACKAGE_PIN T14 [get_ports CAN_0_tx]
set_property PACKAGE_PIN U14 [get_ports CAN_0_rx]
set_property PACKAGE_PIN U15 [get_ports CAN_1_rx]
set_property IOSTANDARD LVCMOS33 [get_ports CAN_0_rx]
set_property IOSTANDARD LVCMOS33 [get_ports CAN_0_tx]
set_property IOSTANDARD LVCMOS33 [get_ports CAN_1_rx]
set_property IOSTANDARD LVCMOS33 [get_ports CAN_1_tx]

set_property IOSTANDARD LVCMOS33 [get_ports UART0_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART0_TX]
set_property PACKAGE_PIN R14 [get_ports UART0_RX]
set_property PACKAGE_PIN V18 [get_ports UART0_TX]
set_property PULLUP true [get_ports UART0_RX]
set_property PULLUP true [get_ports UART0_TX]

set_property PACKAGE_PIN V13 [get_ports iic_0_scl_io]
set_property PACKAGE_PIN U17 [get_ports iic_0_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports iic_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports iic_0_sda_io]
